# -*- coding: utf-8 -*-
"""Project 120.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-BQD1FpoH7Edv3k1p6phx4VXie9BNo3P
"""

from google.colab import files
filesToUpload = files.upload()

import pandas as pd
import csv

df = pd.read_csv("data1.csv")

X = df[["glucose", "bloodpressure"]]
Y = df["diabetes"]

from sklearn.model_selection import train_test_split

X_train_2 , X_test_2, Y_train_2, Y_test_2 = train_test_split(X , Y , test_size = 0.25, random_state = 42)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

SC = StandardScaler()

X_train_2 = SC.fit_transform(X_train_2)
X_test_2 = SC.fit_transform(X_test_2)

model_2 = LogisticRegression(random_state = 0)
model_2.fit(X_train_2, Y_train_2)

accuracy_2 = model_2.predict(X_test_2)
accuracy = accuracy_score(Y_test_2, accuracy_2)

print("The accuracy of data is:", (accuracy)*100, "%")

from google.colab import files
filesToUpload = files.upload()

import pandas as pd
import csv

df = pd.read_csv("data1.csv")

print(df.head())

#Splitting the data into training or testing model
from sklearn.model_selection import train_test_split

X = df[["glucose", "bloodpressure"]]
Y = df["diabetes"]

X_train_1 , X_test_1, Y_train_1, Y_test_1 = train_test_split(X , Y , test_size = 0.25, random_state = 42)

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

SSC = StandardScaler()

X_train_1 = SSC.fit_transform(X_train_1)
X_test_1 = SSC.fit_transform(X_test_1)

model_1 = GaussianNB()
model_1.fit(X_train_1, Y_train_1)

accuracy_1 = model_1.predict(X_test_1)
accuracy = accuracy_score(Y_test_1, accuracy_1)

print("The accuracy of data is:", (accuracy)*100, "%")